Yliu88au patch 1
CERN/TIGRE pull request #206
Opened 2020-12-02 10:24 UTC by yliu88au

Tidy up algorithms in MATLAB

2020-12-02 11:00 UTC, AnderBiguri requested changes
I have added few review to the code. 
Some of it you can directly "aprove" if you like, and some of it its discussion or optional comments. 
Note that changes have to happen/will happen in your side.

2020-12-02 11:20 UTC, AnderBiguri commented on MATLAB/Algorithms/FDK.m
> +%                parker=range(angles)<(2*pi-max(diff(angles)));
```suggestion
```

2020-12-02 11:27 UTC, AnderBiguri commented
Note to self:

This go check in this PR before merging

- [ ] FISTA_mod maths, and see if we can add it to just FISTA
- [ ] FISTA seems changed totally, but not practically, check thaw github is doing (EOL issues?)
- [ ] Test MLEM in python

2020-12-03 22:46 UTC, AnderBiguri commented
@yliu88au , is FISTA_mod the same algorithm as in the paper that is linked in the comments? That paper has several FISTA version, is this one exactly the same as the paper calls "FISTA_mod" ?

2020-12-03 22:56 UTC, yliu88au commented
It is the version of “Lazy-Start”…..

From: Biguri <notifications@github.com>
Sent: Friday, 4 December 2020 9:47 AM
To: CERN/TIGRE <TIGRE@noreply.github.com>
Cc: Liu, Yi (Mineral Resources, Lucas Heights) <Yi.Liu@csiro.au>; Mention <mention@noreply.github.com>
Subject: Re: [CERN/TIGRE] Large MATLAB algorithms tidying, Addition of OS TV algorithms, Modification of FISTA, Python MLEM and few bug fixes (#206)


@yliu88au<https://github.com/yliu88au> , is FISTA_mod the same algorithm as in the paper that is linked in the comments? That paper has several FISTA version, is this one exactly the same as the paper calls "FISTA_mod" ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/CERN/TIGRE/pull/206#issuecomment-738401995>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AR6OBUIFDPLKE5VSBO27SF3STAINDANCNFSM4UKJDEEA>.

2020-12-03 23:05 UTC, yliu88au commented
Perhaps you can make it more general to allow user to set parameter… standard FISTA, “LAZY-START”, etc….

By the way, I just mod and test Python version on newest GPU RTX3090 with CUDA version 11.1, it seems working. But my version of MATLAB does not support this GPU, so I cannot test.

From: Biguri <notifications@github.com>
Sent: Friday, 4 December 2020 9:47 AM
To: CERN/TIGRE <TIGRE@noreply.github.com>
Cc: Liu, Yi (Mineral Resources, Lucas Heights) <Yi.Liu@csiro.au>; Mention <mention@noreply.github.com>
Subject: Re: [CERN/TIGRE] Large MATLAB algorithms tidying, Addition of OS TV algorithms, Modification of FISTA, Python MLEM and few bug fixes (#206)


@yliu88au<https://github.com/yliu88au> , is FISTA_mod the same algorithm as in the paper that is linked in the comments? That paper has several FISTA version, is this one exactly the same as the paper calls "FISTA_mod" ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/CERN/TIGRE/pull/206#issuecomment-738401995>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AR6OBUIFDPLKE5VSBO27SF3STAINDANCNFSM4UKJDEEA>.

2020-12-03 23:11 UTC, AnderBiguri commented
Yeah, that is a good idea. I just need to find the time to go through the code for that. 
I may add it as is and then open issues to tackle later....

Good that you could test in that new GPU!
MATLAB should not care, as unless you changed the compiling to use `mexcuda`, the standard compiler just uses whichever CUDA version you have to compile. You may need to change some flags in the `xml` file, but otherwise it should be able to compile

2020-12-03 23:14 UTC, merged

2020-12-03 23:29 UTC, yliu88au commented
Yeah, I modified xml file and compiled on MATLAB, unfortunately for program to work on new GPU, we do need CUDA 11.1.

From: Biguri <notifications@github.com>
Sent: Friday, 4 December 2020 10:12 AM
To: CERN/TIGRE <TIGRE@noreply.github.com>
Cc: Liu, Yi (Mineral Resources, Lucas Heights) <Yi.Liu@csiro.au>; Mention <mention@noreply.github.com>
Subject: Re: [CERN/TIGRE] Large MATLAB algorithms tidying, Addition of OS TV algorithms, Modification of FISTA, Python MLEM and few bug fixes (#206)


Yeah, that is a good idea. I just need to find the time to go through the code for that.
I may add it as is and then open issues to tackle later....

Good that you could test in that new GPU!
MATLAB should not care, as unless you changed the compiling to use mexcuda, the standard compiler just uses whichever CUDA version you have to compile. You may need to change some flags in the xml file, but otherwise it should be able to compile

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/CERN/TIGRE/pull/206#issuecomment-738437613>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AR6OBUM5WOL3CR3QC2A7HILSTALK7ANCNFSM4UKJDEEA>.

2020-12-03 23:31 UTC, AnderBiguri commented
Yes, of course, but you can install CUDA 11.1 and compile TIGRE-MATLAB using CUDA 11.1 without any issue, that is what I meant.