Offset redundancy weighting
CERN/TIGRE pull request #376
Opened 2022-06-17 15:42 UTC by grupesh

Added data redundancy weighting necessary for offset detector geometry (as an option) in all algorithms, except MLEM, tested with simulation & real data..
also includes 
- fix in V matrix for more stability
- additional fix in zeropadding function for geo.COR

2022-06-17 15:51 UTC, AnderBiguri commented
Thanks a lot!

However, the optional parameter should come in as part of `varargin` as a keyword argument, similar to all the rest of the optional parameters. Can you please put the code there?  Let me know if this needs clarifying.

2022-06-17 15:54 UTC, grupesh commented
Will do this in a bit

2022-06-24 20:48 UTC, grupesh commented
changed redundancy weighting to be part of "varargin". Please review and merge

2022-06-27 11:06 UTC, AnderBiguri requested changes

2022-06-27 11:06 UTC, AnderBiguri commented on MATLAB/Algorithms/FDK.m
> +offset = offset + (geo.DSD(1) / geo.DSO(1)) * geo.COR(1);   % added correction
We should remove `preweighting2()` totally and make `redundacy_weigting()` take the same arguments as `preweighting2()`. That way we don't have redundant code.

2022-06-27 11:06 UTC, AnderBiguri commented on MATLAB/Algorithms/FDK.m
> -            error('TIGRE:FDK:InvalidInput',['Invalid input name:', num2str(opt),'\n No such option in FDK()']);
They should all be `TIGRE` instead of `CBCT`

2022-06-27 11:06 UTC, AnderBiguri commented on MATLAB/Utilities/computeV.m
> -%         maxsize=max(auxgeo.sVoxel+geo.offOrigin(:,auxindex),[],2);
These changes should not be in this PR.

2022-07-05 14:52 UTC, AnderBiguri commented
Hi @grupesh ,

Can I make commits to this branch? I am happy to tackle the reviews myself to add it to TIGRE.

2022-07-05 14:55 UTC, grupesh commented
Sure sure, sorry about the delays on my end..

2022-07-05 14:56 UTC, AnderBiguri commented
@grupesh  absolutely no worries! This is a free contribution to an open source software! Thanks a lot !

2022-08-04 10:13 UTC, AnderBiguri commented
Final question/comment: in the wang weigthts in FDK, they are multiplied by 2 in the end. Is there any reason you have not done this in your `reundacy_weighting()` function? just forgot, or is it better without it?

2022-08-04 10:51 UTC, grupesh commented
I've kept multiplication by 2 in redundancy weighting, same as
preweighting2. I think multiplication by 2 is helpful/necessary, in the
definition of weights in Wang paper, multiplication factor of 2 is present.

Best,
Rupesh

On Thu, Aug 4, 2022, 06:13 Biguri ***@***.***> wrote:

> Final question/comment: in the wang weigthts in FDK, they are multiplied
> by 2 in the end. Is there any reason you have not done this in your
> reundacy_weighting() function? just forgot, or is it better without it?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/CERN/TIGRE/pull/376#issuecomment-1205049356>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AORSFGDEONVRRPVJTJG5C6LVXOJVVANCNFSM5ZCVVKKQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-04 10:57 UTC, AnderBiguri commented
Where is the multiplicatioin happening? I can't see it

2022-08-11 12:12 UTC, AnderBiguri commented
I think this is ready to merge. If you think so too, I will!

Thanks again for the great work.

2022-08-15 16:28 UTC, grupesh commented
Yes, I had forgotten the multiplication by 2 factor, thanks for taking care of that and cleaning up the code. 
I think it's ready to merge.

2022-08-15 16:45 UTC, merged

2022-08-15 16:45 UTC, AnderBiguri commented
Thanks to you for the hard work @grupesh